# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - "2.7"
before_install:
  - pip install -r requirements.txt
install:
  - pip install .
script: py.test
notifications:
  slack:
    secure: "VsB4CPZCfUPpnt7sL94mYrws2B9VthQhY1+u7NBm6QkAopel0m1rx1vWx3gQCTR0t9vWiP+pSybtQ81PQFNrOSWDsb1QlyEK1JF1QUw5Zui+5wS8fwFM/sgwGIECuo6Oj0zCwC9KMM4olYEMC2c7TNHv4HgwWiMqEK9ItEYSLQY="
